name: buildpack-chromedriver

on: push

jobs:
  test:
    runs-on: sfdc-hk-ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Buildpack Compile
      run:  ./bin/compile . . .
